### ISSUE TITLE
DNS Challenge fails - module 'dns.resolver' has no attribute 'resolve'

### ISSUE THREAD

**Issue by 5ebhil** [grindsa/acme2certifier#174] opened 2024-08-09 11:01 UTC
Hello!
When I run the acme.sh with challenge_validation_disable: True, I get no issues at all. But when I change it to false I seem to run in to an issue with the DNS challenge. Here's an output of the journalctl logs from the acme2certifier server: 

> Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore.challenge_lookup(name:ZWQcBrA9h2S0)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore._challenge_search(column:name, pattern:ZWQcBrA9h2S0)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore._challenge_search() ended
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore.challenge_lookup() ended with:{'type': 'dns-01', 'status': 'processing', 'token': 'xzbCODZoPHIP2xV6eGciUrn5WXKo03uP', 'authorization': '13U0nr6cnAVy', 'authorization__type': 'dns', 'authorization__value': 'servername.k8s.company.in>
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore.jwk_load(rLgFo61eXOhW)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore._account_search(column:name, pattern:rLgFo61eXOhW)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore._account_search() ended with: True
Aug 09 10:23:31 acmeserverhostname bash[1523507]: DBStore.jwk_load() ended with: {'crv': 'P-256', 'kty': 'EC', 'x': 'XETkf9QAlHiU-bsS_k_9MXJRyfwOhbRiAdNn3YWRjzQ', 'y': 'AcI5XJL3OCtOG1A8wJ4vR44qWp9vMiqLMVg13M4MkPY', 'alg': 'ES256'}
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._challenge_validate(ZWQcBrA9h2S0)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: jwk_thumbprint_get()
Aug 09 10:23:31 acmeserverhostname bash[1523507]: jwk_thumbprint_get() ended with: fH8laltSqS_R8hyK9P-IRFbadhDXmmXoxKylfjLvasc
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._challenge_validate_loop(ZWQcBrA9h2S0)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._validate_dns_challenge(ZWQcBrA9h2S0:servername.k8s.company.internal:xzbCODZoPHIP2xV6eGciUrn5WXKo03uP)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._wc_manipulate() for fqdn: servername.k8s.company.internal
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._wc_manipulate() ended with: servername.k8s.company.internal
Aug 09 10:23:31 acmeserverhostname bash[1523507]: sha256_hash()
Aug 09 10:23:31 acmeserverhostname bash[1523507]: b64_encode()
Aug 09 10:23:31 acmeserverhostname bash[1523507]: sha256_hash() ended with 3VHPMTLj/MBFbcZeeTtprg4/4/BkYydpY2EwcIi9ozE= (base64-encoded)
Aug 09 10:23:31 acmeserverhostname bash[1523507]: b64_url_encode()
Aug 09 10:23:31 acmeserverhostname bash[1523507]: txt_get(_acme-challenge.servername.k8s.company.internal: ['10.219.17.20', '10.219.19.105'])
Aug 09 10:23:31 acmeserverhostname bash[1523507]: txt_get() error: module 'dns.resolver' has no attribute 'resolve'
Aug 09 10:23:31 acmeserverhostname bash[1523507]: txt_get() ended with: []
Aug 09 10:23:31 acmeserverhostname bash[1523507]: response_got: [] response_expected: b'3VHPMTLj_MBFbcZeeTtprg4_4_BkYydpY2EwcIi9ozE'
Aug 09 10:23:31 acmeserverhostname bash[1523507]: validation not successful
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._validate_dns_challenge() ended with: False
Aug 09 10:23:31 acmeserverhostname bash[1523507]: Challenge._challenge_validate_loop() ended with: False/False
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._challenge_validate_loop(ZWQcBrA9h2S0)
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._validate_dns_challenge(ZWQcBrA9h2S0:servername.k8s.company.internal:xzbCODZoPHIP2xV6eGciUrn5WXKo03uP)
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._wc_manipulate() for fqdn: servername.k8s.company.internal
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._wc_manipulate() ended with: servername.k8s.company.internal
Aug 09 10:23:36 acmeserverhostname bash[1523507]: sha256_hash()
Aug 09 10:23:36 acmeserverhostname bash[1523507]: b64_encode()
Aug 09 10:23:36 acmeserverhostname bash[1523507]: sha256_hash() ended with 3VHPMTLj/MBFbcZeeTtprg4/4/BkYydpY2EwcIi9ozE= (base64-encoded)
Aug 09 10:23:36 acmeserverhostname bash[1523507]: b64_url_encode()
Aug 09 10:23:36 acmeserverhostname bash[1523507]: txt_get(_acme-challenge.servername.k8s.company.internal: ['10.219.17.20', '10.219.19.105'])
Aug 09 10:23:36 acmeserverhostname bash[1523507]: txt_get() error: module 'dns.resolver' has no attribute 'resolve'
Aug 09 10:23:36 acmeserverhostname bash[1523507]: txt_get() ended with: []
Aug 09 10:23:36 acmeserverhostname bash[1523507]: response_got: [] response_expected: b'3VHPMTLj_MBFbcZeeTtprg4_4_BkYydpY2EwcIi9ozE'
Aug 09 10:23:36 acmeserverhostname bash[1523507]: validation not successful
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._validate_dns_challenge() ended with: False
Aug 09 10:23:36 acmeserverhostname bash[1523507]: Challenge._challenge_validate_loop() ended with: False/False
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Challenge._info(ZWQcBrA9h2S0)
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore.challenge_lookup(name:ZWQcBrA9h2S0)
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore._challenge_search(column:name, pattern:ZWQcBrA9h2S0)
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore._challenge_search() ended
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore.challenge_lookup() ended with:{'type': 'dns-01', 'token': 'xzbCODZoPHIP2xV6eGciUrn5WXKo03uP', 'status': 'processing', 'validated': 0}
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Challenge._info(ZWQcBrA9h2S0) ended
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Challenge._parse() ended with: 200
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Message.prepare_response()
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Nonce.nonce_generate_and_add()
Aug 09 10:23:41 acmeserverhostname bash[1523507]: Nonce.nonce__new()
Aug 09 10:23:41 acmeserverhostname bash[1523507]: got nonce: 48fbfdb7132842e4b1a33f0198658f44
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore.nonce_add(48fbfdb7132842e4b1a33f0198658f44)
Aug 09 10:23:41 acmeserverhostname bash[1523507]: DBStore.nonce_add() ended

Here's the acme_srv.cfg:

[DEFAULT]
debug: True

[Nonce]
nonce_check_disable: False

[CAhandler]
handler_file: examples/ca_handler/mswcce_ca_handler.py
host: < ca-server >
user: < username >
password: < password >
target_domain: < domain >
domain_controller: < domain controller ip >
ca_name: < ca name >
ca_bundle: /etc/pki/ca-trust/source/anchors/< ca-bundle >
template: < template >
use_kerberos: True

[Certificate]
revocation_reason_check_disable: False

[Challenge]
challenge_validation_disable: False
dns_server_list: ["< primary dns ip >","< secondary dns ip >"]
dns_validation_pause_timer: 5

[Order]
tnauthlist_support: False

Please let me know if you need more information!
Thanks in advance!

**Comment by grindsa** [comment] 2024-08-09 13:51
Hi,

Can you please describe your deployment a bid more in detail? Are you running a container/rpm/deb/manual installation? If its not in a container, whats your host-os?

BR /G.

**Comment by 5ebhil** [comment] 2024-08-12 08:00
Thanks for your rapid response!

Acme2certifier is running on a RHEL 8.9 vm in RHEV (I followed the "RPM installation on AlmaLinux/Redhat EL/CentOS Stream 9" instructions) and we are using the acme.sh and Cert Manager on a Kubernetes cluster. We do run Microsoft DNS and have them configured in the acme_srv.cfg, and we also have two Bind DNS servers running RHEL 9.2 on the Kubernetes cluster in a separate DNS zone, forwarding to our primary domain DNS (same as CA-root).

I hope this helps and gives you an idea on how it's setup. Please let me know if you need anything else.

**Comment by grindsa** [comment] 2024-08-12 11:26
Hi, 

Thx, the issue is related to your python3-dns package. The one coming with RH8 is version [1.x](https://rpmfind.net/linux/RPM/centos/8-stream/baseos/x86_64/Packages/python3-dns-1.15.0-10.el8.noarch.html) but you need version 2.  I created an [own backport from RH9](https://github.com/grindsa/sbom/raw/main/rpm-repo/RPMs/rhel8/python3-dns-2.1.0-6.el8.noarch.rpm) for regressing testing. Feel free to use it. SRPM can be found [here](rpm-repo/SRPMs).

Let me add some sentences in the above-mentioned installation guide. You are not the first one coming across this issue.

BR G.

**Comment by 5ebhil** [comment] 2024-08-15 06:34
It seems like that did the trick! Thank you very much!

**Comment by grindsa** [comment] 2024-08-15 13:33
thank you for confirming. Closing the issue then.

**Closed by grindsa** 2024-08-15 13:33 UTC
Labels: compatibility issue
